#!/bin/bash
function usage {
cat >> /dev/stdout << EOF
wifi is a simple wrapper around nmcli.
Specifically for connecting to wifi.
Usage: 
       wifi
It will then prompt asking if this is
a pre-existing router or not.
It will then prompt for the router name
(SSID) and then the password.
The password is suppressed for security.
EOF
exit
}
function create_pass_hash(){
    passw=$1
    wf_dev=$2
    touch tmp_pass && chmod 600 tmp_pass
    echo $passw > tmp_pass
    echo -n $(sha256sum tmp_pass | awk '{print $1}') >> .wifi.key
    echo " ${wf_dev}" >> .wifi.key
    shred -zu tmp_pass
}

[ $# -ne 0 ] && [ $1 == "-h" ] && usage

echo 'Are we logging into an existing wifi router? [y/n]'
read -s ans

echo "What is tne name of the WiFi device:"
read wf_dev
echo "Please enter the password:"
read -s pass

case $ans in 
y|Y|yes|Yes|YES)
    touch tmp_pass && chmod 600 tmp_pass
    echo $pass > tmp_pass
    check1=$(sha256sum tmp_pass | awk '{print $1}')
    check2=$(grep ${wf_dev} .wifi.key | awk '{print $1}')
    shred -zu tmp_pass
    [ -z $check2 ] && echo "Check that SSID is Correct" && usage
    [ $check1 == $check2 ] || echo "Bad password" || usage
    ;;
n|N|no|No|NO)
    create_pass_hash $pass $wf_dev
    ;;
*)
    echo "Bad Input"
    usage
esac

sudo nmcli dev wifi connect ${wf_dev} password ${pass}
